[2023-12-30T11:20:29.264+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_model.run_dbt_silver_models scheduled__2022-09-10T00:00:00+00:00 [queued]>
[2023-12-30T11:20:29.272+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_model.run_dbt_silver_models scheduled__2022-09-10T00:00:00+00:00 [queued]>
[2023-12-30T11:20:29.272+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-30T11:20:29.272+0000] {taskinstance.py:1363} INFO - Starting attempt 5 of 6
[2023-12-30T11:20:29.272+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-30T11:20:29.283+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): run_dbt_silver_models> on 2022-09-10 00:00:00+00:00
[2023-12-30T11:20:29.287+0000] {standard_task_runner.py:55} INFO - Started process 7119 to run task
[2023-12-30T11:20:29.289+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_model', 'run_dbt_silver_models', 'scheduled__2022-09-10T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt._models.py', '--cfg-path', '/tmp/tmppvou8bjr']
[2023-12-30T11:20:29.290+0000] {standard_task_runner.py:83} INFO - Job 124: Subtask run_dbt_silver_models
[2023-12-30T11:20:29.331+0000] {task_command.py:376} INFO - Running <TaskInstance: dbt_model.run_dbt_silver_models scheduled__2022-09-10T00:00:00+00:00 [running]> on host 683423f116e7
[2023-12-30T11:20:29.374+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alonso_md
AIRFLOW_CTX_DAG_ID=dbt_model
AIRFLOW_CTX_TASK_ID=run_dbt_silver_models
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T00:00:00+00:00
[2023-12-30T11:20:29.379+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-12-30T11:20:29.379+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "    dbt run     --profiles-dir //opt/***/dags/../dbt/     --project-dir ///opt/***/dags/../dbt//dwh     --target prod_*** --vars '{ target_date: 2022-09-10 }' --select silver"]
[2023-12-30T11:20:29.386+0000] {subprocess.py:86} INFO - Output:
[2023-12-30T11:20:31.089+0000] {subprocess.py:93} INFO - [0m11:20:31  Running with dbt=1.4.6
[2023-12-30T11:20:31.181+0000] {subprocess.py:93} INFO - [0m11:20:31  Found 8 models, 15 tests, 0 snapshots, 0 analyses, 703 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
[2023-12-30T11:20:31.182+0000] {subprocess.py:93} INFO - [0m11:20:31
[2023-12-30T11:20:31.242+0000] {subprocess.py:93} INFO - [0m11:20:31  Concurrency: 4 threads (target='prod_***')
[2023-12-30T11:20:31.243+0000] {subprocess.py:93} INFO - [0m11:20:31
[2023-12-30T11:20:31.248+0000] {subprocess.py:93} INFO - [0m11:20:31  1 of 3 START sql incremental model silver.customer_information ................. [RUN]
[2023-12-30T11:20:31.250+0000] {subprocess.py:93} INFO - [0m11:20:31  2 of 3 START sql incremental model silver.daily_customer_drivers ............... [RUN]
[2023-12-30T11:20:31.252+0000] {subprocess.py:93} INFO - [0m11:20:31  3 of 3 START sql incremental model silver.loan_transactions .................... [RUN]
[2023-12-30T11:20:31.344+0000] {subprocess.py:93} INFO - [0m11:20:31  2 of 3 ERROR creating sql incremental model silver.daily_customer_drivers ...... [[31mERROR[0m in 0.09s]
[2023-12-30T11:20:31.495+0000] {subprocess.py:93} INFO - [0m11:20:31  3 of 3 OK created sql incremental model silver.loan_transactions ............... [[32mINSERT 0 9613[0m in 0.24s]
[2023-12-30T11:20:31.515+0000] {subprocess.py:93} INFO - [0m11:20:31  1 of 3 OK created sql incremental model silver.customer_information ............ [[32mINSERT 0 28497[0m in 0.27s]
[2023-12-30T11:20:31.573+0000] {subprocess.py:93} INFO - [0m11:20:31
[2023-12-30T11:20:31.574+0000] {subprocess.py:93} INFO - [0m11:20:31  Finished running 3 incremental models in 0 hours 0 minutes and 0.39 seconds (0.39s).
[2023-12-30T11:20:31.584+0000] {subprocess.py:93} INFO - [0m11:20:31
[2023-12-30T11:20:31.584+0000] {subprocess.py:93} INFO - [0m11:20:31  [31mCompleted with 1 error and 0 warnings:[0m
[2023-12-30T11:20:31.584+0000] {subprocess.py:93} INFO - [0m11:20:31
[2023-12-30T11:20:31.585+0000] {subprocess.py:93} INFO - [0m11:20:31  [33mDatabase Error in model daily_customer_drivers (models/silver/daily_customer_drivers.sql)[0m
[2023-12-30T11:20:31.585+0000] {subprocess.py:93} INFO - [0m11:20:31    operator does not exist: text < integer
[2023-12-30T11:20:31.585+0000] {subprocess.py:93} INFO - [0m11:20:31    LINE 22:         WHEN health_score < 100 THEN 100
[2023-12-30T11:20:31.585+0000] {subprocess.py:93} INFO - [0m11:20:31                                       ^
[2023-12-30T11:20:31.586+0000] {subprocess.py:93} INFO - [0m11:20:31    HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
[2023-12-30T11:20:31.586+0000] {subprocess.py:93} INFO - [0m11:20:31    compiled Code at target/run/dwh/models/silver/daily_customer_drivers.sql
[2023-12-30T11:20:31.586+0000] {subprocess.py:93} INFO - [0m11:20:31
[2023-12-30T11:20:31.586+0000] {subprocess.py:93} INFO - [0m11:20:31  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
[2023-12-30T11:20:32.468+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-30T11:20:32.476+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-30T11:20:32.481+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_model, task_id=run_dbt_silver_models, execution_date=20220910T000000, start_date=20231230T112029, end_date=20231230T112032
[2023-12-30T11:20:32.493+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 124 for task run_dbt_silver_models (Bash command failed. The command returned a non-zero exit code 1.; 7119)
[2023-12-30T11:20:32.514+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-30T11:20:32.556+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-30T12:37:15.879+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_model.run_dbt_silver_models scheduled__2022-09-10T00:00:00+00:00 [queued]>
[2023-12-30T12:37:15.918+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_model.run_dbt_silver_models scheduled__2022-09-10T00:00:00+00:00 [queued]>
[2023-12-30T12:37:15.918+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-30T12:37:15.919+0000] {taskinstance.py:1363} INFO - Starting attempt 5 of 6
[2023-12-30T12:37:15.919+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-30T12:37:15.962+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): run_dbt_silver_models> on 2022-09-10 00:00:00+00:00
[2023-12-30T12:37:15.976+0000] {standard_task_runner.py:55} INFO - Started process 11051 to run task
[2023-12-30T12:37:15.986+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_model', 'run_dbt_silver_models', 'scheduled__2022-09-10T00:00:00+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt._models.py', '--cfg-path', '/tmp/tmp7va466b8']
[2023-12-30T12:37:15.987+0000] {standard_task_runner.py:83} INFO - Job 132: Subtask run_dbt_silver_models
[2023-12-30T12:37:16.203+0000] {task_command.py:376} INFO - Running <TaskInstance: dbt_model.run_dbt_silver_models scheduled__2022-09-10T00:00:00+00:00 [running]> on host 683423f116e7
[2023-12-30T12:37:16.402+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alonso_md
AIRFLOW_CTX_DAG_ID=dbt_model
AIRFLOW_CTX_TASK_ID=run_dbt_silver_models
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T00:00:00+00:00
[2023-12-30T12:37:16.404+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-12-30T12:37:16.407+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "    dbt run     --profiles-dir //opt/***/dags/../dbt/     --project-dir ///opt/***/dags/../dbt//dwh     --target prod_*** --vars '{ target_date: 2022-09-10 }' --select silver"]
[2023-12-30T12:37:16.432+0000] {subprocess.py:86} INFO - Output:
[2023-12-30T12:37:20.499+0000] {subprocess.py:93} INFO - [0m12:37:20  Running with dbt=1.4.6
[2023-12-30T12:37:20.694+0000] {subprocess.py:93} INFO - [0m12:37:20  Found 8 models, 15 tests, 0 snapshots, 0 analyses, 703 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
[2023-12-30T12:37:20.697+0000] {subprocess.py:93} INFO - [0m12:37:20
[2023-12-30T12:37:20.841+0000] {subprocess.py:93} INFO - [0m12:37:20  Concurrency: 4 threads (target='prod_***')
[2023-12-30T12:37:20.842+0000] {subprocess.py:93} INFO - [0m12:37:20
[2023-12-30T12:37:20.857+0000] {subprocess.py:93} INFO - [0m12:37:20  1 of 3 START sql incremental model silver.customer_information ................. [RUN]
[2023-12-30T12:37:20.861+0000] {subprocess.py:93} INFO - [0m12:37:20  2 of 3 START sql incremental model silver.daily_customer_drivers ............... [RUN]
[2023-12-30T12:37:20.873+0000] {subprocess.py:93} INFO - [0m12:37:20  3 of 3 START sql incremental model silver.loan_transactions .................... [RUN]
[2023-12-30T12:37:21.244+0000] {subprocess.py:93} INFO - [0m12:37:21  2 of 3 ERROR creating sql incremental model silver.daily_customer_drivers ...... [[31mERROR[0m in 0.37s]
[2023-12-30T12:37:21.668+0000] {subprocess.py:93} INFO - [0m12:37:21  3 of 3 OK created sql incremental model silver.loan_transactions ............... [[32mINSERT 0 9613[0m in 0.79s]
[2023-12-30T12:37:21.693+0000] {subprocess.py:93} INFO - [0m12:37:21  1 of 3 OK created sql incremental model silver.customer_information ............ [[32mINSERT 0 28497[0m in 0.83s]
[2023-12-30T12:37:21.801+0000] {subprocess.py:93} INFO - [0m12:37:21
[2023-12-30T12:37:21.801+0000] {subprocess.py:93} INFO - [0m12:37:21  Finished running 3 incremental models in 0 hours 0 minutes and 1.10 seconds (1.10s).
[2023-12-30T12:37:21.827+0000] {subprocess.py:93} INFO - [0m12:37:21
[2023-12-30T12:37:21.828+0000] {subprocess.py:93} INFO - [0m12:37:21  [31mCompleted with 1 error and 0 warnings:[0m
[2023-12-30T12:37:21.829+0000] {subprocess.py:93} INFO - [0m12:37:21
[2023-12-30T12:37:21.830+0000] {subprocess.py:93} INFO - [0m12:37:21  [33mDatabase Error in model daily_customer_drivers (models/silver/daily_customer_drivers.sql)[0m
[2023-12-30T12:37:21.830+0000] {subprocess.py:93} INFO - [0m12:37:21    operator does not exist: text < integer
[2023-12-30T12:37:21.831+0000] {subprocess.py:93} INFO - [0m12:37:21    LINE 22:         WHEN health_score < 100 THEN 100
[2023-12-30T12:37:21.832+0000] {subprocess.py:93} INFO - [0m12:37:21                                       ^
[2023-12-30T12:37:21.832+0000] {subprocess.py:93} INFO - [0m12:37:21    HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
[2023-12-30T12:37:21.833+0000] {subprocess.py:93} INFO - [0m12:37:21    compiled Code at target/run/dwh/models/silver/daily_customer_drivers.sql
[2023-12-30T12:37:21.834+0000] {subprocess.py:93} INFO - [0m12:37:21
[2023-12-30T12:37:21.835+0000] {subprocess.py:93} INFO - [0m12:37:21  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
[2023-12-30T12:37:22.931+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-30T12:37:22.948+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-30T12:37:22.953+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_model, task_id=run_dbt_silver_models, execution_date=20220910T000000, start_date=20231230T123715, end_date=20231230T123722
[2023-12-30T12:37:22.974+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 132 for task run_dbt_silver_models (Bash command failed. The command returned a non-zero exit code 1.; 11051)
[2023-12-30T12:37:22.986+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-30T12:37:23.050+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-30T14:27:41.542+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_model.run_dbt_silver_models scheduled__2022-09-10T00:00:00+00:00 [queued]>
[2023-12-30T14:27:41.552+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_model.run_dbt_silver_models scheduled__2022-09-10T00:00:00+00:00 [queued]>
[2023-12-30T14:27:41.553+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-30T14:27:41.553+0000] {taskinstance.py:1363} INFO - Starting attempt 5 of 6
[2023-12-30T14:27:41.553+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-30T14:27:41.563+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): run_dbt_silver_models> on 2022-09-10 00:00:00+00:00
[2023-12-30T14:27:41.568+0000] {standard_task_runner.py:55} INFO - Started process 16596 to run task
[2023-12-30T14:27:41.570+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_model', 'run_dbt_silver_models', 'scheduled__2022-09-10T00:00:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt._models.py', '--cfg-path', '/tmp/tmpuj9n9kv9']
[2023-12-30T14:27:41.571+0000] {standard_task_runner.py:83} INFO - Job 141: Subtask run_dbt_silver_models
[2023-12-30T14:27:41.612+0000] {task_command.py:376} INFO - Running <TaskInstance: dbt_model.run_dbt_silver_models scheduled__2022-09-10T00:00:00+00:00 [running]> on host 683423f116e7
[2023-12-30T14:27:41.661+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alonso_md
AIRFLOW_CTX_DAG_ID=dbt_model
AIRFLOW_CTX_TASK_ID=run_dbt_silver_models
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T00:00:00+00:00
[2023-12-30T14:27:41.665+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-12-30T14:27:41.665+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "    dbt run     --profiles-dir //opt/***/dags/../dbt/     --project-dir ///opt/***/dags/../dbt//dwh     --target prod_*** --vars '{ target_date: 2022-09-10 }' --select silver"]
[2023-12-30T14:27:41.674+0000] {subprocess.py:86} INFO - Output:
[2023-12-30T14:27:43.655+0000] {subprocess.py:93} INFO - [0m14:27:43  Running with dbt=1.4.6
[2023-12-30T14:27:43.809+0000] {subprocess.py:93} INFO - [0m14:27:43  Found 8 models, 15 tests, 0 snapshots, 0 analyses, 703 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
[2023-12-30T14:27:43.811+0000] {subprocess.py:93} INFO - [0m14:27:43
[2023-12-30T14:27:43.881+0000] {subprocess.py:93} INFO - [0m14:27:43  Concurrency: 4 threads (target='prod_***')
[2023-12-30T14:27:43.881+0000] {subprocess.py:93} INFO - [0m14:27:43
[2023-12-30T14:27:43.889+0000] {subprocess.py:93} INFO - [0m14:27:43  1 of 3 START sql incremental model silver.customer_information ................. [RUN]
[2023-12-30T14:27:43.890+0000] {subprocess.py:93} INFO - [0m14:27:43  2 of 3 START sql incremental model silver.daily_customer_drivers ............... [RUN]
[2023-12-30T14:27:43.891+0000] {subprocess.py:93} INFO - [0m14:27:43  3 of 3 START sql incremental model silver.loan_transactions .................... [RUN]
[2023-12-30T14:27:43.983+0000] {subprocess.py:93} INFO - [0m14:27:43  2 of 3 ERROR creating sql incremental model silver.daily_customer_drivers ...... [[31mERROR[0m in 0.09s]
[2023-12-30T14:27:44.101+0000] {subprocess.py:93} INFO - [0m14:27:44  3 of 3 ERROR creating sql incremental model silver.loan_transactions ........... [[31mERROR[0m in 0.21s]
[2023-12-30T14:27:44.103+0000] {subprocess.py:93} INFO - [0m14:27:44  1 of 3 ERROR creating sql incremental model silver.customer_information ........ [[31mERROR[0m in 0.21s]
[2023-12-30T14:27:44.205+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.205+0000] {subprocess.py:93} INFO - [0m14:27:44  Finished running 3 incremental models in 0 hours 0 minutes and 0.39 seconds (0.39s).
[2023-12-30T14:27:44.218+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.219+0000] {subprocess.py:93} INFO - [0m14:27:44  [31mCompleted with 3 errors and 0 warnings:[0m
[2023-12-30T14:27:44.219+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.220+0000] {subprocess.py:93} INFO - [0m14:27:44  [33mDatabase Error in model daily_customer_drivers (models/silver/daily_customer_drivers.sql)[0m
[2023-12-30T14:27:44.220+0000] {subprocess.py:93} INFO - [0m14:27:44    relation "bronze.raw_daily_customer_drivers" does not exist
[2023-12-30T14:27:44.221+0000] {subprocess.py:93} INFO - [0m14:27:44    LINE 11:     SELECT * FROM "dwh"."bronze"."raw_daily_customer_drivers...
[2023-12-30T14:27:44.221+0000] {subprocess.py:93} INFO - [0m14:27:44                               ^
[2023-12-30T14:27:44.221+0000] {subprocess.py:93} INFO - [0m14:27:44    compiled Code at target/run/dwh/models/silver/daily_customer_drivers.sql
[2023-12-30T14:27:44.222+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.222+0000] {subprocess.py:93} INFO - [0m14:27:44  [33mCompilation Error in model loan_transactions (models/silver/loan_transactions.sql)[0m
[2023-12-30T14:27:44.222+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.223+0000] {subprocess.py:93} INFO - [0m14:27:44                  The source and target schemas on this incremental model are out of sync!
[2023-12-30T14:27:44.223+0000] {subprocess.py:93} INFO - [0m14:27:44                  They can be reconciled in several ways:
[2023-12-30T14:27:44.223+0000] {subprocess.py:93} INFO - [0m14:27:44                    - set the `on_schema_change` config to either append_new_columns or sync_all_columns, depending on your situation.
[2023-12-30T14:27:44.224+0000] {subprocess.py:93} INFO - [0m14:27:44                    - Re-run the incremental model with `full_refresh: True` to update the target schema.
[2023-12-30T14:27:44.224+0000] {subprocess.py:93} INFO - [0m14:27:44                    - update the schema manually and re-run the process.
[2023-12-30T14:27:44.224+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.224+0000] {subprocess.py:93} INFO - [0m14:27:44                  Additional troubleshooting context:
[2023-12-30T14:27:44.225+0000] {subprocess.py:93} INFO - [0m14:27:44                     Source columns not in target: []
[2023-12-30T14:27:44.225+0000] {subprocess.py:93} INFO - [0m14:27:44                     Target columns not in source: []
[2023-12-30T14:27:44.225+0000] {subprocess.py:93} INFO - [0m14:27:44                     New column types: [{'column_name': 'paymentperiod', 'new_type': 'double precision'}]
[2023-12-30T14:27:44.225+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.226+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.226+0000] {subprocess.py:93} INFO - [0m14:27:44    > in macro process_schema_changes (macros/materializations/models/incremental/on_schema_change.sql)
[2023-12-30T14:27:44.226+0000] {subprocess.py:93} INFO - [0m14:27:44    > called by macro materialization_incremental_default (macros/materializations/models/incremental/incremental.sql)
[2023-12-30T14:27:44.226+0000] {subprocess.py:93} INFO - [0m14:27:44    > called by model loan_transactions (models/silver/loan_transactions.sql)
[2023-12-30T14:27:44.227+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.227+0000] {subprocess.py:93} INFO - [0m14:27:44  [33mCompilation Error in model customer_information (models/silver/customer_information.sql)[0m
[2023-12-30T14:27:44.227+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.227+0000] {subprocess.py:93} INFO - [0m14:27:44                  The source and target schemas on this incremental model are out of sync!
[2023-12-30T14:27:44.228+0000] {subprocess.py:93} INFO - [0m14:27:44                  They can be reconciled in several ways:
[2023-12-30T14:27:44.228+0000] {subprocess.py:93} INFO - [0m14:27:44                    - set the `on_schema_change` config to either append_new_columns or sync_all_columns, depending on your situation.
[2023-12-30T14:27:44.228+0000] {subprocess.py:93} INFO - [0m14:27:44                    - Re-run the incremental model with `full_refresh: True` to update the target schema.
[2023-12-30T14:27:44.228+0000] {subprocess.py:93} INFO - [0m14:27:44                    - update the schema manually and re-run the process.
[2023-12-30T14:27:44.229+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.229+0000] {subprocess.py:93} INFO - [0m14:27:44                  Additional troubleshooting context:
[2023-12-30T14:27:44.229+0000] {subprocess.py:93} INFO - [0m14:27:44                     Source columns not in target: []
[2023-12-30T14:27:44.229+0000] {subprocess.py:93} INFO - [0m14:27:44                     Target columns not in source: []
[2023-12-30T14:27:44.230+0000] {subprocess.py:93} INFO - [0m14:27:44                     New column types: [{'column_name': 'is_active', 'new_type': 'boolean'}]
[2023-12-30T14:27:44.230+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.230+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.230+0000] {subprocess.py:93} INFO - [0m14:27:44    > in macro process_schema_changes (macros/materializations/models/incremental/on_schema_change.sql)
[2023-12-30T14:27:44.231+0000] {subprocess.py:93} INFO - [0m14:27:44    > called by macro materialization_incremental_default (macros/materializations/models/incremental/incremental.sql)
[2023-12-30T14:27:44.231+0000] {subprocess.py:93} INFO - [0m14:27:44    > called by model customer_information (models/silver/customer_information.sql)
[2023-12-30T14:27:44.231+0000] {subprocess.py:93} INFO - [0m14:27:44
[2023-12-30T14:27:44.231+0000] {subprocess.py:93} INFO - [0m14:27:44  Done. PASS=0 WARN=0 ERROR=3 SKIP=0 TOTAL=3
[2023-12-30T14:27:45.103+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-30T14:27:45.113+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-30T14:27:45.116+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_model, task_id=run_dbt_silver_models, execution_date=20220910T000000, start_date=20231230T142741, end_date=20231230T142745
[2023-12-30T14:27:45.130+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 141 for task run_dbt_silver_models (Bash command failed. The command returned a non-zero exit code 1.; 16596)
[2023-12-30T14:27:45.154+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-30T14:27:45.190+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
